"""Pre-registration is the highest-value constraint in the system, so the rule
that implements it gets tested harder than anything else."""

from __future__ import annotations

import pytest

from ml_research_agent.config import ExperimentsConfig
from ml_research_agent.experiments.spec import validate_spec
from ml_research_agent.types import (
    DatasetRef,
    DecisionRule,
    ExperimentSpec,
    MetricDef,
    VerdictStatus,
)


def rule(**overrides) -> DecisionRule:
    defaults = dict(metric="accuracy", comparator=">", threshold=0.01, min_seeds=3)
    return DecisionRule(**{**defaults, **overrides})


def spec(**overrides) -> ExperimentSpec:
    defaults = dict(
        hypothesis_id="hyp",
        title="t",
        dependent_variables=[MetricDef(name="accuracy")],
        dataset=DatasetRef(name="toy"),
        baselines=["baseline"],
        treatment="treatment",
        controls=["matched compute"],
        seeds=[0, 1, 2],
        decision_rule=rule(),
    )
    return ExperimentSpec(**{**defaults, **overrides})


class TestDecisionRuleEvaluation:
    def test_clears_threshold_with_enough_seeds_is_supported(self):
        assert rule().evaluate(0.05, p_value=0.01, seeds=3) is VerdictStatus.SUPPORTED

    def test_misses_threshold_is_refuted_not_inconclusive(self):
        # A real measurement that failed the bar is a finding, not a shrug.
        assert rule().evaluate(0.001, p_value=0.01, seeds=3) is VerdictStatus.REFUTED

    def test_too_few_seeds_is_inconclusive_by_construction(self):
        assert rule().evaluate(0.5, p_value=0.001, seeds=1) is VerdictStatus.INCONCLUSIVE

    def test_missing_p_value_when_required_is_inconclusive(self):
        assert rule().evaluate(0.5, p_value=None, seeds=5) is VerdictStatus.INCONCLUSIVE

    def test_p_value_above_ceiling_is_inconclusive(self):
        assert (
            rule(max_p_value=0.05).evaluate(0.5, p_value=0.4, seeds=5) is VerdictStatus.INCONCLUSIVE
        )

    def test_effect_below_minimum_size_is_refuted(self):
        r = rule(threshold=0.0, min_effect_size=0.1)
        assert r.evaluate(0.02, p_value=0.001, seeds=5) is VerdictStatus.REFUTED

    def test_no_p_value_requirement_allows_evaluation_without_one(self):
        r = rule(max_p_value=None)
        assert r.evaluate(0.5, p_value=None, seeds=3) is VerdictStatus.SUPPORTED

    @pytest.mark.parametrize(
        ("comparator", "effect", "expected"),
        [
            (">", 0.02, VerdictStatus.SUPPORTED),
            (">", -0.02, VerdictStatus.REFUTED),
            ("<", -0.02, VerdictStatus.SUPPORTED),
            ("<", 0.02, VerdictStatus.REFUTED),
            (">=", 0.01, VerdictStatus.SUPPORTED),
            ("<=", 0.01, VerdictStatus.REFUTED),
        ],
    )
    def test_comparators(self, comparator, effect, expected):
        r = rule(comparator=comparator, threshold=0.01 if comparator in (">", ">=") else -0.01)
        assert r.evaluate(effect, p_value=0.001, seeds=3) is expected

    def test_statement_is_autogenerated_when_absent(self):
        assert "Refuted unless" in rule().statement

    def test_explicit_statement_is_preserved(self):
        assert rule(statement="my own words").statement == "my own words"


class TestSpecPolicyValidation:
    def test_a_well_formed_spec_passes(self):
        assert validate_spec(spec(), ExperimentsConfig()) == []

    def test_single_seed_spec_is_rejected(self):
        problems = validate_spec(
            spec(seeds=[0], decision_rule=rule(min_seeds=1)), ExperimentsConfig()
        )
        assert any("single-seed" in p for p in problems)

    def test_rule_on_an_unmeasured_metric_is_rejected(self):
        problems = validate_spec(spec(decision_rule=rule(metric="f1")), ExperimentsConfig())
        assert any("not measured" in p for p in problems)

    def test_fewer_seeds_than_the_rule_requires_is_rejected(self):
        problems = validate_spec(
            spec(seeds=[0, 1], decision_rule=rule(min_seeds=5)), ExperimentsConfig()
        )
        assert any("requires 5" in p for p in problems)

    def test_treatment_that_is_also_a_baseline_is_rejected(self):
        problems = validate_spec(
            spec(baselines=["treatment"], treatment="treatment"), ExperimentsConfig()
        )
        assert any("vacuous" in p for p in problems)

    def test_missing_controls_are_rejected(self):
        problems = validate_spec(spec(controls=[]), ExperimentsConfig())
        assert any("controls" in p for p in problems)

    def test_preregistration_can_be_required(self):
        unregistered = spec()
        object.__setattr__(unregistered.decision_rule, "statement", "")
        problems = validate_spec(
            unregistered, ExperimentsConfig(require_preregistered_decision_rule=True)
        )
        assert any("pre-registered" in p for p in problems)


class TestSpecHash:
    def test_identity_is_stable_across_objects(self):
        assert spec().spec_hash == spec().spec_hash

    def test_hash_ignores_ids_and_timestamps(self):
        a, b = spec(), spec(title="t")
        assert a.id != b.id
        assert a.spec_hash == b.spec_hash

    def test_hash_changes_when_the_experiment_changes(self):
        assert spec().spec_hash != spec(seeds=[0, 1, 2, 3]).spec_hash
        assert spec().spec_hash != spec(decision_rule=rule(threshold=0.5)).spec_hash
        assert spec().spec_hash != spec(baselines=["other"]).spec_hash

    def test_hash_ignores_budget(self):
        # Budget is a policy knob, not part of the experiment's identity.
        assert spec(budget_usd=1.0).spec_hash == spec(budget_usd=99.0).spec_hash

    def test_seeds_are_normalized_so_order_does_not_change_identity(self):
        assert spec(seeds=[2, 0, 1]).spec_hash == spec(seeds=[0, 1, 2]).spec_hash
